# https://alacritty.org/config-alacritty.html

# [general]
# import = []
# working_directory   = "None"
# live_config_reload  = true
# ipc_socket          = false

# [env]
# TERM = "xterm-256color"

[window]
dimensions            = { columns = 120, lines = 35 }
# position              = "None"
padding               = { x = 5, y = 5 }
# dynamic_padding       = false
# decorations           = "Full"
# opacity               = 1.0
# blur                  = false
# startup_mode          = "Maximized"
# title                 = "Alacritty"
# dynamic_title         = true
# class                 = { instance = "Alacritty", general = "Alacritty" }
# decorations_theme_variant = "None"
# resize_increments     = false
# option_as_alt         = "None"

[scrolling]
history               = 100000
#multiplier            = 3

[font]
normal                = { family = "CommitMono Nerd Font Mono", style = "Regular" }
bold                  = { family = "Bitstream Vera Sans Mono", style = "Bold" }
italic                = { family = "CommitMono Nerd Font Mono", style = "Italic" }
bold_italic           = { family = "CommitMono Nerd Font Mono", style = "Bold Italic" }
size                  = 9.5
offset                = { x = 0, y = 2 }
# glyph_offset          = { x = 0, y = 0 }
# builtin_box_drawing   = true

[colors.primary]
foreground            = "#f8f8f8"
background            = "#272727"
# dim_foreground        = "#828482"
# bright_foreground     = "None"

# [colors.cursor]
# text                  = "CellBackground"
# cursor                = "CellForeground"

# [colors.vi_mode_cursor]
# text                  = "CellForeground"
# cursor                = "CellForeground"

# [colors.search.matches]
# foreground            = "#181818"
# background            = "#ac4242"

# [colors.search.focused_match]
# foreground            = "#181818"
# background            = "#f4bf75"

# [colors.hints.start]
# foreground            = "#181818"
# background            = "#f4bf75"

# [colors.hints.end]
# foreground            = "#181818"
# background            = "#ac4242"

# [colors.line_indicator]
# foreground            = "None"
# background            = "None"

# [colors.footer_bar]
# foreground            = "#181818"
# background            = "#d8d8d8"

# [colors.selection]
# text                  = "CellBackground"
# background            = "CellBackground"

# [colors.normal]
# black                 = "#181818"
# red                   = "#ac4242"
# green                 = "#90a959"
# yellow                = "#f4bf75"
# blue                  = "#6a9fb5"
# magenta               = "#aa759f"
# cyan                  = "#75b5aa"
# white                 = "#d8d8d8"

# [colors.bright]
# black                 = "#6b6b6b"
# red                   = "#c55555"
# green                 = "#aac474"
# yellow                = "#feca88"
# blue                  = "#82b8c8"
# magenta               = "#c28cb8"
# cyan                  = "#93d3c3"
# white                 = "#f8f8f8"

# [colors.dim]
# black                 = "#0f0f0f"
# red                   = "#712b2b"
# green                 = "#5f6f3a"
# yellow                = "#a17e4d"
# blue                  = "#456877"
# magenta               = "#704d68"
# cyan                  = "#4d7770"
# white                 = "#8e8e8e"

# [colors]
# indexed_colors = []
# transparent_background_colors = false
# draw_bold_text_with_bright_colors = false

# [bell]
# animation             = "Linear"
# duration              = 0
# color                 = "#ffffff"
# command               = "None"

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true

[cursor.style]
# shape                 = "Block"
blinking              = "Never"

# [cursor]
# vi_mode_style         = "None"
# blink_interval        = 750
# blink_timeout         = 5
# unfocused_hollow      = true
# thickness             = 0.15

# [terminal]
# shell = {program = "/usr/bin/fish", args = []}
# osc52 = "OnlyCopy"

[mouse]
# hide_when_typing = false
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

# [hints]
# alphabet = "jfkdls;ahgurieowpq"

#[[hints.enabled]]
#command               = "xdg-open"
## command             = "open" # On macOS
## command             = { program = "cmd", args = [ "/c", "start", "" ] } # On Windows
#hyperlinks            = true
#post_processing       = true
#persist               = false
#mouse.enabled         = true
#binding               = { key = "U", mods = "Control|Shift" }
#regex                 = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  # { key = "V",        mods = "Control|Shift", action = "Paste" },
  # { key = "C",        mods = "Control|Shift", action = "Copy" },
  # { key = "Paste",                            action = "Paste" },
  # { key = "Copy",                             action = "Copy" },
  # { key = "Insert",   mods = "Shift",         action = "PasteSelection" },
  # { key = "F",        mods = "Control|Shift", action = "SearchForward",     mode = "~Search" },
  # { key = "B",        mods = "Control|Shift", action = "SearchBackward",    mode = "~Search" },
  # { key = "Key0",     mods = "Control",       action = "ResetFontSize" },
  # { key = "Equals",   mods = "Control",       action = "IncreaseFontSize" },
  # { key = "Minus",    mods = "Control",       action = "DecreaseFontSize" },
  # { key = "L",        mods = "Control",       action = "ClearLogNotice" },
  # { key = "L",        mods = "Control",       chars  = "\f" },
  # { key = "PageUp",   mods = "Shift",         action = "ScrollPageUp",      mode = "~Alt" },
  # { key = "PageDown", mods = "Shift",         action = "ScrollPageDown",    mode = "~Alt" },
  # { key = "Up",       mods = "Shift",         action = "ScrollLineUp",      mode = "~Alt" },
  # { key = "Down",     mods = "Shift",         action = "ScrollLineDown",    mode = "~Alt" },
  # { key = "Home",     mods = "Shift",         action = "ScrollToTop",       mode = "~Alt" },
  # { key = "End",      mods = "Shift",         action = "ScrollToBottom",    mode = "~Alt" },
]

# [debug]
#render_timer          = false
#persistent_logging    = false
#log_level             = "Warn"
#renderer              = "None"
#print_events          = false
#highlight_damage      = false
#prefer_egl            = false
